app:
  name: my-backend-api

dependencies:
  - type: mongodb
    name: ids
    version: 3.4
    size: 500MB
  - type: mongodb
    name: catalog
    version: 3.4
    size: 3GB
  - type: elasticsearch
    name: websearch
    version: 7.1
    size: 5GB
