app:
  name: my-backend-api
  type: java
  version: 8

dependencies:
  - type: mongodb
    name: my-ids
    version: 3.4
    size: 500MB
  - type: mongodb
    name: my-catalog
    version: 3.4
    size: 3GB
  - type: elasticsearch
    name: my-websearch
    version: 7.1
    size: 5GB
  - type: redis
    name: my-super-redis
    version: 5
    size: 100MB
