qovery:
  key: jtme9xokl7cc63cp/dfq6imouvrqsy8zx/ju23hr9xfiaw4ovq
application:
  name: my-backend-api
  project: test-back-java
  publicly_accessible: true
databases:
- name: my-pql
  type: postgresql
  version: 11.5
brokers:
- name: my-rabbit
  type: rabbitmq
  version: 3.8
